# Generated by Django 3.0.7 on 2020-06-28 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0002_auto_20200628_0206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='code',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
